#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MIN_SYMBOLS_IN_STRING 1
#define MAX_SYMBOLS_IN_STRING 1000
#define MIN_NUMBER_OF_STRINGS 1
#define MAX_NUMBER_OF_STRINGS 10000
#define SPACE_SYMBOL_CODE 32
#define TILDA_SYMBOL_CODE 126

#endif // CONSTANTS_H
